spring.application.name=devflow-ai

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/devflow_ai
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckRldkZsb3dBSUJWTlQxMjM0NTY3ODkw
jwt.expiration=86400000

logging.level.com.yogesh.devflow=DEBUG
logging.level.org.springframework.security=TRACE