spring.application.name=devflow-ai

# =========================
# PostgreSQL Configuration
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/devflow_ai
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA Configuration
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Server Configuration
# =========================
server.port=8080

# =========================
# JWT Configuration
# =========================
jwt.secret=VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckRldkZsb3dBSUJWTlQxMjM0NTY3ODkw
jwt.expiration=86400000